baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Lockwood's blog"
theme="material-design"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
#disqusShortname = "Your Disqus Name" # optional
copyright = "© 2015 Copyright John Lockwood"

[params]
  description = "Your Site Description" # optional
  twitter = "@johnwlockwoodiv" # optional
  github = "johnwlockwood" # optional
  linkedin = "johnwlockwood" # optional
  headerCover = "images/headerCover.png" # optional
  footerCover = "images/footerCover.png" # optional
  #googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
